# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
#  - name: Demo
#    url: '#about'
#    weight: 10
  - name: Publications
    url: '#publications'
    weight: 10
  - name: Interventions
    url: '#publications'
    weight: 20
  - name: Séminaires
    url: courses/
    weight: 30
  - name: Projets
    url: '#projects'
    weight: 40
#  - name: Blog
#    url: '#posts'
#    weight: 50
#  - name: Talks
#    url: '#talks'
#    weight: 50
  - name: Contact
    url: '#contact'
    weight: 60
