# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
#  - name: Demo
#    url: '#about'
#    weight: 10
  - name: Publications
    url: publication/
    weight: 10
  - name: Traductions
    url: translation/
    weight: 20   
  - name: Séminaires
    url: courses/
    weight: 30
  - name: Projets
    url: project/
    weight: 40
#  - name: Talks
#    url: '#talks'
#    weight: 50
  - name: À-côtés
    url: intervention/
    weight: 60
#  - name: Blog
#    url: '#posts'
#    weight: 70    
  - name: Contact
    url: '#contact'
    weight: 80
